const T = {
  en:{deliver:"Deliver to India",tagline:"100% Pure & Chemical-Free Herbal Powders",hello:"Hello, sign in",signin:"Account",cart:"Cart",menu:"Menu",bestsellers:"Bestsellers",deals:"Today's Deals","new":"New Releases",sale:"Sale",all:"All Products",eyebrow:"Root to Jar, Naturally",hero1:"Pure herbal powders,",hero2:"grown with intention.",herop:"Sun-dried, stone-ground and bottled by hand — every jar of Sunvora carries the full strength of the root, leaf or seed it came from. No fillers. No shortcuts.",shopnow:"Shop the Collection",search:"Search herbal powders…",bestsellers2:"Bestsellers",deals2:"Today's Deals",new2:"New Releases"},
  hi:{deliver:"भारत में डिलीवरी",tagline:"100% शुद्ध और रसायन-मुक्त हर्बल पाउडर",hello:"नमस्ते, साइन इन करें",signin:"खाता",cart:"कार्ट",menu:"मेनू",bestsellers:"बेस्टसेलर",deals:"आज के ऑफर","new":"नए उत्पाद",sale:"सेल",all:"सभी उत्पाद",eyebrow:"जड़ से जार तक, स्वाभाविक रूप से",hero1:"शुद्ध हर्बल पाउडर,",hero2:"प्रेम से उगाए गए।",herop:"धूप में सुखाया और पत्थर पर पिसा — हर जार में जड़, पत्ती या बीज की पूरी ताकत। कोई मिलावट नहीं।",shopnow:"अभी खरीदें",search:"हर्बल पाउडर खोजें…",bestsellers2:"बेस्टसेलर",deals2:"आज के ऑफर",new2:"नए उत्पाद"},
  mr:{deliver:"भारतात डिलिव्हरी",tagline:"100% शुद्ध हर्बल पावडर",hello:"नमस्कार, साइन इन करा",signin:"खाते",cart:"कार्ट",menu:"मेनू",bestsellers:"बेस्टसेलर",deals:"आजचे ऑफर","new":"नवीन",sale:"सेल",all:"सर्व उत्पादने",eyebrow:"मूळापासून जारपर्यंत",hero1:"शुद्ध हर्बल पावडर,",hero2:"मनापासून पिकवलेली.",herop:"उन्हात वाळवलेली आणि दगडावर दळलेली — प्रत्येक बरणी मुळाची, पानाची किंवा बीजाची पूर्ण ताकद देते.",shopnow:"आता खरेदी करा",search:"हर्बल पावडर शोधा…",bestsellers2:"बेस्टसेलर",deals2:"आजचे ऑफर",new2:"नवीन"},
  ta:{deliver:"இந்தியாவிற்கு டெலிவரி",tagline:"100% தூய மூலிகைத் தூள்கள்",hello:"வணக்கம், உள்நுழையவும்",signin:"கணக்கு",cart:"கூடை",menu:"மெனு",bestsellers:"சிறந்த விற்பனை",deals:"இன்றைய சலுகைகள்","new":"புதியவை",sale:"விற்பனை",all:"அனைத்து பொருட்கள்",eyebrow:"வேரிலிருந்து ஜாடிக்கு",hero1:"தூய மூலிகைத் தூள்கள்,",hero2:"அக்கறையுடன் வளர்க்கப்பட்டவை.",herop:"வெயிலில் உலர்த்தி, கல்லில் அரைத்து — ஒவ்வொரு ஜாடியிலும் முழு வலிமை.",shopnow:"இப்போது வாங்கவும்",search:"மூலிகைத் தூள்களைத் தேடுங்கள்…",bestsellers2:"சிறந்த விற்பனை",deals2:"இன்றைய சலுகைகள்",new2:"புதியவை"},
  te:{deliver:"భారతదేశానికి డెలివరీ",tagline:"100% స్వచ్ఛమైన హెర్బల్ పొడులు",hello:"హలో, సైన్ ఇన్ చేయండి",signin:"ఖాతా",cart:"కార్ట్",menu:"మెనూ",bestsellers:"బెస్ట్ సెల్లర్స్",deals:"నేటి ఆఫర్లు","new":"కొత్తవి",sale:"సేల్",all:"అన్ని ఉత్పత్తులు",eyebrow:"వేరు నుండి జార్ వరకు",hero1:"స్వచ్ఛమైన హెర్బల్ పొడులు,",hero2:"శ్రద్ధతో పండించినవి.",herop:"ఎండలో ఆరబెట్టి, రాతిపై రుబ్బినవి — ప్రతి జార్‌లో పూర్తి శక్తి.",shopnow:"ఇప్పుడు కొనండి",search:"హెర్బల్ పొడులను వెతకండి…",bestsellers2:"బెస్ట్ సెల్లర్స్",deals2:"నేటి ఆఫర్లు",new2:"కొత్తవి"},
  bn:{deliver:"ভারতে ডেলিভারি",tagline:"১০০% খাঁটি হারবাল পাউডার",hello:"হ্যালো, সাইন ইন করুন",signin:"অ্যাকাউন্ট",cart:"কার্ট",menu:"মেনু",bestsellers:"বেস্টসেলার",deals:"আজকের অফার","new":"নতুন",sale:"সেল",all:"সব পণ্য",eyebrow:"শিকড় থেকে জার পর্যন্ত",hero1:"খাঁটি হারবাল পাউডার,",hero2:"যত্ন সহকারে চাষ করা।",herop:"রোদে শুকানো, পাথরে গুঁড়ো করা — প্রতিটি জারে পূর্ণ শক্তি।",shopnow:"এখনই কিনুন",search:"হারবাল পাউডার খুঁজুন…",bestsellers2:"বেস্টসেলার",deals2:"আজকের অফার",new2:"নতুন"},
  gu:{deliver:"ભારતમાં ડિલિવરી",tagline:"૧૦૦% શુદ્ધ હર્બલ પાવડર",hello:"નમસ્તે, સાઇન ઇન કરો",signin:"ખાતું",cart:"કાર્ટ",menu:"મેનુ",bestsellers:"બેસ્ટસેલર",deals:"આજની ઓફર","new":"નવું",sale:"સેલ",all:"બધા ઉત્પાદનો",eyebrow:"મૂળથી બરણી સુધી",hero1:"શુદ્ધ હર્બલ પાવડર,",hero2:"કાળજીપૂર્વક ઉગાડેલા.",herop:"તડકામાં સૂકવેલા, પથ્થર પર દળેલા — દરેક બરણીમાં પૂરી તાકાત.",shopnow:"હમણાં ખરીદો",search:"હર્બલ પાવડર શોધો…",bestsellers2:"બેસ્ટસેલર",deals2:"આજની ઓફર",new2:"નવું"},
  kn:{deliver:"ಭಾರತಕ್ಕೆ ವಿತರಣೆ",tagline:"100% ಶುದ್ಧ ಗಿಡಮೂಲಿಕೆ ಪುಡಿಗಳು",hello:"ನಮಸ್ಕಾರ, ಸೈನ್ ಇನ್ ಮಾಡಿ",signin:"ಖಾತೆ",cart:"ಕಾರ್ಟ್",menu:"ಮೆನು",bestsellers:"ಬೆಸ್ಟ್‌ಸೆಲ್ಲರ್",deals:"ಇಂದಿನ ಡೀಲ್‌ಗಳು","new":"ಹೊಸವು",sale:"ಮಾರಾಟ",all:"ಎಲ್ಲಾ ಉತ್ಪನ್ನಗಳು",eyebrow:"ಬೇರಿನಿಂದ ಜಾರ್‌ವರೆಗೆ",hero1:"ಶುದ್ಧ ಗಿಡಮೂಲಿಕೆ ಪುಡಿಗಳು,",hero2:"ಕಾಳಜಿಯಿಂದ ಬೆಳೆಸಿದವು.",herop:"ಬಿಸಿಲಿನಲ್ಲಿ ಒಣಗಿಸಿ, ಕಲ್ಲಿನಲ್ಲಿ ರುಬ್ಬಿದ — ಪ್ರತಿ ಜಾರ್‌ನಲ್ಲಿ ಪೂರ್ಣ ಶಕ್ತಿ.",shopnow:"ಈಗ ಖರೀದಿಸಿ",search:"ಗಿಡಮೂಲಿಕೆ ಪುಡಿಗಳನ್ನು ಹುಡುಕಿ…",bestsellers2:"ಬೆಸ್ಟ್‌ಸೆಲ್ಲರ್",deals2:"ಇಂದಿನ ಡೀಲ್‌ಗಳು",new2:"ಹೊಸವು"},
  ml:{deliver:"ഇന്ത്യയിലേക്ക് ഡെലിവറി",tagline:"100% ശുദ്ധമായ ഹെർബൽ പൊടികൾ",hello:"ഹലോ, സൈൻ ഇൻ ചെയ്യുക",signin:"അക്കൗണ്ട്",cart:"കാർട്ട്",menu:"മെനു",bestsellers:"ബെസ്റ്റ്‌സെല്ലർ",deals:"ഇന്നത്തെ ഓഫറുകൾ","new":"പുതിയവ",sale:"സെയിൽ",all:"എല്ലാ ഉൽപ്പന്നങ്ങളും",eyebrow:"വേരിൽ നിന്ന് ജാറിലേക്ക്",hero1:"ശുദ്ധമായ ഹെർബൽ പൊടികൾ,",hero2:"കരുതലോടെ വളർത്തിയത്.",herop:"വെയിലിൽ ഉണക്കി, കല്ലിൽ പൊടിച്ചത് — ഓരോ ജാറിലും പൂർണ്ണ ശക്തി.",shopnow:"ഇപ്പോൾ വാങ്ങുക",search:"ഹെർബൽ പൊടികൾ തിരയുക…",bestsellers2:"ബെസ്റ്റ്‌സെല്ലർ",deals2:"ഇന്നത്തെ ഓഫറുകൾ",new2:"പുതിയവ"},
  pa:{deliver:"ਭਾਰਤ ਵਿੱਚ ਡਿਲੀਵਰੀ",tagline:"100% ਸ਼ੁੱਧ ਹਰਬਲ ਪਾਊਡਰ",hello:"ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਸਾਈਨ ਇਨ ਕਰੋ",signin:"ਖਾਤਾ",cart:"ਕਾਰਟ",menu:"ਮੀਨੂ",bestsellers:"ਬੈਸਟਸੈਲਰ",deals:"ਅੱਜ ਦੇ ਸੌਦੇ","new":"ਨਵੇਂ",sale:"ਸੇਲ",all:"ਸਾਰੇ ਉਤਪਾਦ",eyebrow:"ਜੜ੍ਹ ਤੋਂ ਜਾਰ ਤੱਕ",hero1:"ਸ਼ੁੱਧ ਹਰਬਲ ਪਾਊਡਰ,",hero2:"ਧਿਆਨ ਨਾਲ ਉਗਾਏ ਗਏ.",herop:"ਧੁੱਪ ਵਿੱਚ ਸੁਕਾਏ, ਪੱਥਰ ਤੇ ਪੀਸੇ — ਹਰ ਜਾਰ ਵਿੱਚ ਪੂਰੀ ਤਾਕਤ।",shopnow:"ਹੁਣੇ ਖਰੀਦੋ",search:"ਹਰਬਲ ਪਾਊਡਰ ਖੋਜੋ…",bestsellers2:"ਬੈਸਟਸੈਲਰ",deals2:"ਅੱਜ ਦੇ ਸੌਦੇ",new2:"ਨਵੇਂ"}
};
function applyLanguage(lang) {
  const d = T[lang] || T.en;
  const map = {"i18n-deliver":"deliver","i18n-tagline":"tagline","i18n-hello":"hello","i18n-signin":"signin","i18n-cart":"cart","i18n-menu":"menu","i18n-bestsellers":"bestsellers","i18n-deals":"deals","i18n-new":"new","i18n-sale":"sale","i18n-all":"all","i18n-eyebrow":"eyebrow","i18n-hero1":"hero1","i18n-hero2":"hero2","i18n-herop":"herop","i18n-shopnow":"shopnow","i18n-bestsellers2":"bestsellers2","i18n-deals2":"deals2","i18n-new2":"new2"};
  Object.keys(map).forEach(id => {
    const el = document.getElementById(id);
    if (el && d[map[id]]) el.textContent = d[map[id]];
  });
  const si = document.getElementById('searchInput');
  if (si && d.search) si.placeholder = d.search;
  localStorage.setItem('sunvora_lang', lang);
}
